services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: metlife
      POSTGRES_USER: sisrael
      POSTGRES_PASSWORD: challenge123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sisrael -d metlife"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: metlife
      DB_USER: sisrael
      DB_PASS: challenge123
      CSV_PATH: /app/dataset.csv
      
      MODEL_PATH: /app/modelo_xgboost_final.pkl

volumes:
  pgdata: